name: scroll_edge_hint_example
description: Example app for scroll_edge_hint
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  scroll_edge_hint:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
